name: Github Contexts
run-name: custom workflow run name - ${{inputs.debug}}

on:
  push:
  workflow_dispatch:
    inputs:  
      debug:
        type: boolean
        default: false

env:
  WORKFLOW_VAR: 'workflow'
  OVERWRITTEN_VAR: 'workflow'

jobs:
  echo-data:
    runs-on: ubuntu-latest
    env:
      JOB_VAR: 'job'
      OVERWRITTEN_VAR: 'job'
    steps:
      - name: display information
        run: |
          echo "Event name: ${{github.event_name}}"
          echo "Ref: ${{github.ref}}"
          echo "SHA: ${{github.sha}}"
          echo "Workflow: ${{github.workflow}}"
          echo "Run ID: ${{github.run_id}}"
          echo "Run number: ${{github.run_number}}"
      - name: retrieve variables
        run: |
            echo "Variable Value: ${{vars.MY_VAR}}"
      - name: print env variable
        env:
          OVERWRITEN_VAR: 'steps'
        run: |
          echo "Workflow env: ${{env.WORKFLOW_VAR}}"
          echo "Overwritten env: ${{env.OVERWRITTEN_VAR}}"

      - name: print env variable
        run: |
          echo "Workflow env: ${{env.WORKFLOW_VAR}}"
          echo "Overwritten env: ${{env.OVERWRITTEN_VAR}}"
  echo-data2:
    runs-on: ubuntu-latest
    steps:
      - name: print env variable
        run: |
          echo "Workflow env: ${{env.WORKFLOW_VAR}}"
          echo "Overwritten env: ${{env.OVERWRITTEN_VAR}}"   